version: '3.7'

services:
  
  influxdb:
    image: influxdb:1.7.5
    network_mode: host
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    ports:
      - "8086:8086"
    volumes:
      - ./data:/var/lib/influxdb

  prometheus:
    image: prom/prometheus:v2.8.1
    network_mode: host
    depends_on: 
      - influxdb
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
  
  cAdvisor:
    image: google/cadvisor:v0.33.0
    network_mode: host
    ports:
      - "8080:8080"
    command: --enable_load_reader=true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  alertManager:
    image: prom/alertmanager:v0.16.1
    network_mode: host
    depends_on: 
      - prometheus
    ports:
      - "9093:9093"
    command: --config.file /etc/alertmanager/alertmanager.yml
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  grafana:
    image: grafana/grafana:5.2.2
    network_mode: host
    user: 1000:1000
    depends_on: 
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana





