global:
  scrape_interval:     15s

  external_labels:
    monitor: 'prometheus-gdg'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'
    
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9100']
  
  - job_name: 'cAdvisor'
    
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:8080']

remote_write:
  - url: "http://localhost:8086/api/v1/prom/write?db=YOUR_DB&u=YOUR_USER&p=YOUR_PASSWORD"

remote_read:
  - url: "http://localhost:8086/api/v1/prom/read?db=YOUR_DB&u=YOUR_USER&p=YOUR_PASSWORD"

rule_files:
  - "/etc/prometheus/alert.rules.yml"